version: '3.8'

services:
  ticketing-api:
    build: .
    container_name: ticketing-api
    ports:
      - "5000:80"
    volumes:
      - ./TicketingApp:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - ticketing_network

  db:
    image: nouchka/sqlite
    container_name: ticketing-db
    volumes:
      - ticketing-data:/app/data
    networks:
      - ticketing_network

networks:
  ticketing_network:
    driver: bridge

volumes:
  ticketing-data:
    driver: local
